Structural analysis/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Structural_analysis.Models;
using System.Diagnostics;

namespace Structural_analysis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SectionCalculations()
        {
            return View();
        }

        public IActionResult InWork()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Structural analysis/Controllers/SteelSectionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Structural_analysis.Models;
using Structural_analysis.Models.SteelBeams;
using Structural_analysis.ViewModel;

namespace Structural_analysis.Controllers
{
    public class SteelSectionController : Controller
    {
        public IActionResult SteelISection()
        {
            SteelISectionModel model = new SteelISectionModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult SteelISection(SteelISectionModel model)
        {
            StrengthSteelISection results = new StrengthSteelISection(model.width1Top, model.thick1Top, model.width2Top, model.thick2Top, 
            model.width3Top, model.thick3Top, model.width1Bottom, model.thick1Bottom, model.width2Bottom, model.thick2Bottom, 
            model.width3Bottom, model.thick3Bottom, model.wallHeight, model.wallThick, model.steelType, model.Mmax, model.Q1, model.Mmin, 
            model.Q2, model.m);

            model.Ry = results.Ry * results.m;
            model.Rs = results.Rs * results.m;          

            model.SigmaXMaxBottom = results.SigmaXBottom(results.Mmax, results.Q1);
            model.SigmaXMaxTop = results.SigmaXTop(results.Mmax, results.Q1);
            model.SigmaXMinBottom = results.SigmaXBottom(results.Mmin, results.Q2);
            model.SigmaXMinTop = results.SigmaXTop(results.Mmin, results.Q2);

            model.TauM1 = results.TauM(results.Q1);
            model.TauM2 = results.TauM(results.Q2);

            model.kappa1 = results.kappa1();

            model.kappa_1 = results.kappa(results.Q1);
            model.kappa_2 = results.kappa(results.Q2);

            model.Qcritical1 = results.Qcritical(results.Q1);
            model.Qcritical2 = results.Qcritical(results.Q2);

            model.momentOfInertion = results.MomentOfInertionX;
            model.yMassCentre = results.YMassCentre;

            return View(model); 
        }

        public IActionResult SteelISectionOrtPlate()
        {
            SteelISectionOrtPlateModel model = new SteelISectionOrtPlateModel();
            return View(model);
        }
        [HttpPost]
        public IActionResult SteelISectionOrtPlate(SteelISectionOrtPlateModel model)
        {
            StrengthSteelISectionOrtPlate results = new StrengthSteelISectionOrtPlate(model.width1Top, model.thick1Top, model.width2Top, 
                model.thick2Top, model.width3Top, model.thick3Top, model.width1Bottom, model.thick1Bottom, model.width2Bottom, 
                model.thick2Bottom, model.width3Bottom, model.thick3Bottom, model.wallHeight, model.wallThick, model.widthOrtPlateTopLeft, 
                model.thickOrtPlateTopLeft, model.widthOrtPlateTopRight, model.thickOrtPlateTopRight, model.widthOrtPlateBottomLeft, 
                model.thickOrtPlateBottomLeft, model.widthOrtPlateBottomRight, model.thickOrtPlateBottomRight, model.hStringerTop, 
                model.thickStringerTop, model.numberOfTopStringersLeft, model.numberOfTopStringersRight, model.hStringerBottom, 
                model.thickStringerBottom, model.numberOfBottomStringersLeft, model.numberOfBottomStringersRight, model.yOrtPlateTop, 
                model.yOrtPlateBottom, model.steelType, model.Mmax, model.Q1, model.Mmin, model.Q2, model.m);

            model.Ry = results.Ry * results.m;
            model.Rs = results.Rs * results.m;

            model.SigmaXMaxBottom = results.SigmaXBottom(results.Mmax, results.Q1);
            model.SigmaXMaxTop = results.SigmaXTop(results.Mmax, results.Q1);
            model.SigmaXMinBottom = results.SigmaXBottom(results.Mmin, results.Q2);
            model.SigmaXMinTop = results.SigmaXTop(results.Mmin, results.Q2);

            model.TauM1 = results.TauM(results.Q1);
            model.TauM2 = results.TauM(results.Q2);

            model.kappa1 = results.kappa1();

            model.kappa_1 = results.kappa(results.Q1);
            model.kappa_2 = results.kappa(results.Q2);

            model.Qcritical1 = results.Qcritical(results.Q1);
            model.Qcritical2 = results.Qcritical(results.Q2);

            model.momentOfInertion = results.MomentOfInertionX;
            model.yMassCentre = results.YMassCentre;

            return View(model);
        }
        public IActionResult Test()
        {
            return View();
        }
    }
}

Structural analysis/Views/Home/InWork.cshtml
@{
    ViewData["Title"] = "Раздел находится в разработке";
}
<h1>@ViewData["Title"]</h1>

Structural analysis/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
<div>
    <h1 class="display-4">Портал для расчета мостовых конструкций</h1>
</div>
<div>
    <div class="bridge">
        <p>
            Добро пожаловать на портал, созданный для расчета конструкций мостов в соответствии с действующими нормативными документами.
            На данный момент основным документом по которому выполняются расчета является СП 35.13330.2011 Актуализированная редакция.
        </p>
        <p>
            В случае обнаружения багов просим связаться с разработчиками.
        </p>
    </div>
    <div class="bridge">
        <img id="img1" src=~/img/home/Bridge.png />
    </div>
</div>

Structural analysis/Views/Home/SectionCalculations.cshtml
@{
    ViewData["Title"] = "Расчеты сечений";
}
<h1>@ViewData["Title"]</h1>
<div>
    <ul>
        <li>
            <h3>Стальные мосты</h3>
            <ul>
                <li><a asp-area="" asp-controller="SteelSection" asp-action="SteelISection">Балочный мост (без ортотропной плиты)</a></li>
                <li><a asp-area="" asp-controller="SteelSection" asp-action="SteelISectionOrtPlate">Балочный мост (с ортотропной плитой)</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Ферма</a></li>
            </ul>
        </li>
        <li>
            <h3>Сталежелезобетонные мосты</h3>
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Двутавровое сечение</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Коробчатое сечение</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Ферма</a></li>
            </ul>
        </li>
        <li>
            <h3>Железобетонные мосты</h3>
            <ul>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Типовой проект (без предварительного натяжения)</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Типовой проект (с предварительным натяжением)</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Коробчатое сечение (без предварительного натяжения)</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="InWork">Коробчатое сечение (с предварительным натяжением)</a></li>
            </ul>
        </li>
    </ul>
</div>